version: 2

formats: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
